# Generated by Django 4.2.3 on 2023-07-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='galary', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
